name: data visualizations
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: create visualization reports
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # run the script that generates the plots
          # python my_scripts/plot.py

          # basic description of the plots
          echo "# Univariate analysis" >> report.md

          # Post reports as comments in GitHub PRs
          echo "## Sales across state holidays" >> report.md
          cml publish plots/univariate_9.JPG --md >> report.md

          echo "## Sales and customers across store types" >> report.md
          cml publish univariate_1.JPG --md >> report.md

          echo "## Sales and customers across promotion interval" >> report.md
          cml publish univariate_2.JPG >> report.md

          echo "## Sales across competition distance" >> report.md
          cml publish univariate_3.JPG --md >> report.md

          echo "## Top seven features and sales corelation" >> report.md
          cml publish univariate_4.JPG --md >> report.md

          echo "## Sales across store type, promotion and month" >> report.md
          cml publish univariate_6.JPG --md >> report.md

          echo "## Sales across assortment, promotion and month" >> report.md
          cml publish univariate_8.JPG --md >> report.md

          cml send-comment report.md

